version: '3'
services:

  flask:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: flask
    image: amazon_web_scrap/flask-python:3.6
    restart: always
    environment:
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: product_data
      MONGODB_USERNAME: sellerapp
      MONGODB_PASSWORD: sellerapp
      MONGODB_HOSTNAME: mongodb
    volumes:
      - appdata:/var/www
    depends_on:
      - mongodb 
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: always
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: sellerapp
      MONGO_INITDB_ROOT_PASSWORD: sellerapp
      MONGO_INITDB_DATABASE: product_data
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: amazon_web_scrap/webserver:latest
    container_name: webserver
    restart: always
    environment:
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "80:80"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - flask
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local
